<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <script>
        fetch("http://httpstat.us/500")
    .then(function(response) {
        if (!response.ok) {
            throw Error(response.statusText);
        }
        return response;
    }).then(function(response) {
        console.log("ok");
    }).catch(function(error) {
        console.log(error);
    });
    </script>
</body>
</html>


<!-- the fetch() API only rejects a promise when a “network error is encountered, 
although this usually means permissions issues or similar.” 
Basically fetch() will only reject a promise if the user is offline, 
or some unlikely networking error occurs, such a DNS lookup failure.

The good is news is fetch provides a simple ok flag that indicates whether an HTTP response’s 
status code is in the successful range or not. 
For instance the following code logs “Error: Internal Server Error(…)”: -->